version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached

    container_name: htwbot
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
